name: "check-version-upgrade"
description: "check if you have upgraded the version of your project"
inputs:
  repo_name:
    description: "package name"
    required: true
    default: "${{ github.event.repository.name }}"
  repo_owner:
   description: "repo owner name"
   required: true
   default: "${{ github.repository_owner }}"
  branch: 
    description: "branch name"
    required: true
    default: "${{ github.sha }}"

runs:
  using: "node16"
  main: "dist/index.js"